config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get 'tasks', to: 'tasks#index'
  get 'tasks/new', to: 'tasks#new'
  get 'tasks/:id', to: 'tasks#show', as: 'task'
  post 'tasks', to: 'tasks#create'
  get 'tasks/:id/edit', to: 'tasks#edit', as: 'edit'
  patch 'tasks/:id', to: 'tasks#update'
  delete 'tasks/:id', to: 'tasks#destroy', as: 'destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
  def init
    self.completed || false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path, status: :see_other
  end

  private

  def task_params
    params.require(:task).permit(:title, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <div class="m-3">
    <%= yield %>
  </div>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit task</h1>
<%= form_for(@task) do |t| %>
  <%= t.label :title %>
  <%= t.text_field :title %>
  <%= t.label :details %>
  <%= t.text_field :details %>
  <%= t.submit %>
<% end %>
<div class="mt-3">
<%= link_to "← Back to list", tasks_path %>
</div>

app/views/tasks/index.html.erb
<h1>My tasks</h1>
<ul>
  <% @tasks.each do |task| %>
    <li><%= link_to task.title, task_path(task.id) %></li>
  <% end %>
</ul>
<hr>
<p><%= link_to "+ Add new task", tasks_new_path %></p>

app/views/tasks/new.html.erb
<h1>New task</h1>
<%= form_for(@task) do |t| %>
  <%= t.label :title %>
  <%= t.text_field :title %>
  <%= t.label :details %>
  <%= t.text_field :details %>
  <%= t.submit %>
<% end %>
<div class="mt-3">
<%= link_to "← Back to list", tasks_path %>
</div>

app/views/tasks/show.html.erb
<ul class="navbar list-unstyled">
  <li><h1><%= @task.title  %></h1></li>
  <li><%= link_to '✏️Edit the task', edit_path %></li>
</ul>

<h3><%= @task.details %></h3>
<input type="checkbox" id="completed" name="completed">
<label for="completed">This task is completed</label>
<hr>
<%= link_to "Delete",
  destroy_path,
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
%>

<hr>
<%= link_to "← Back to list", tasks_path %>